### ISSUE TITLE
Add project license

### ISSUE THREAD

**Issue by wilkmaia** [wilkmaia/minigrep#2]

**Comment by hails** [comment]
What license do you have in mind?

**Comment by wilkmaia** [comment]
@macabu opened https://github.com/wilkmaia/minigrep/pull/8 adding an MIT license to the project.

I had something similar in mind: something permissive.

Still open to suggestions, though.

**Comment by macabu** [comment]
Or we could use WTFPL :100:  
Free as in "do whatever the fuck you want"

**Comment by hails** [comment]
I think we should just stick with MIT's, because just werks.

**Comment by wilkmaia** [comment]
I'd stick with MIT as well. If no one is against it, let's move on with #8 :)

**Comment by macabu** [comment]
:+1: for MIT
